server:
  port: 8081

spring:

  application:
    name: spring-security

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false

app:
  secretKey: JWTSuperSecretKey
  jwtExpireTimeInMS: 604800000

