server:
  port: ${PORT}

spring:

  profiles:
    active: prod

  datasource:
    url: ${JDBC_URL}
    driverClassName: ${DRIVER_CLASS}
    username: ${USERNAME}
    password: ${PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

spring-security:
  client:
    redirect-url: ${REDIRECT_URL}
    client-urls: ${CLIENT_URLS}