spring:
  application:
    name: spring-security

  profiles:
    active: @spring.profiles.active@

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    servlet:
      content-type: text/html

jwt:
  refreshToken:
    expiresIn: 172800000
    secretKey: bZnoIcVsWCM7HvjTSMaNJ26SPsXBMU5pHzu8NxWIU1XkxCw1vn
  accessToken:
    expiresIn: 86400000
    secretKey: ulll60BDXyO3OoGHuaRikY4ESOgXnrEotljOc4uJEI1ZZWlsKr

spring-security:
  swagger:
    base-package: org.personal.spring.security
    base-path: "/api.*"