spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  liquibase:
    change-log: classpath:liquibase/master.xml

spring-security:
  client:
    redirect-url: http://localhost:3000