server:
  port: 8081

spring:

  application:
    name: spring-security

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:liquibase/master.xml
  h2:
    console:
      enabled: true
      path: /h2

app:
  secretKey: JWTSuperSecretKey
  jwtExpireTimeInMS: 86400000

