server:
  port: 8081

spring:
  application:
    name: spring-security

  profiles:
    active: @spring.profiles.active@

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    servlet:
      content-type: text/html

spring-security:
  jwt:
    secret-key: JWTSuperSecretKey
    expiry-time: 86400000
  swagger:
    base-package: org.personal.spring.security
    base-path: "/api.*"